(define (problem tpp-manual-1)
(:domain TPP-Propositional)
(:objects
	l0 l1 l2 l3 - level
	jefferson - depot
	shoprite marketbasket - market
	red-truck blue-truck - truck
	blueberries apples grapes lemons strawberries oranges mangos - goods
)
(:init
	(next l1 l0)
	(next l2 l1)
	(next l3 l2)
	(ready-to-load blueberries shoprite l0)
	(ready-to-load blueberries marketbasket l0)
	(ready-to-load apples shoprite l0)
	(ready-to-load apples marketbasket l0)
	(ready-to-load grapes shoprite l0)
	(ready-to-load grapes marketbasket l0)
	(ready-to-load lemons shoprite l0)
	(ready-to-load lemons marketbasket l0)
	(ready-to-load strawberries shoprite l0)
	(ready-to-load strawberries marketbasket l0)
	(ready-to-load oranges shoprite l0)
	(ready-to-load oranges marketbasket l0)
	(ready-to-load mangos shoprite l0)
	(ready-to-load mangos marketbasket l0)
	(stored blueberries l0)
	(stored apples l0)
	(stored grapes l0)
	(stored lemons l0)
	(stored strawberries l0)
	(stored oranges l0)
	(stored mangos l0)
	(loaded blueberries red-truck l0)
	(loaded blueberries blue-truck l0)
	(loaded apples red-truck l0)
	(loaded apples blue-truck l0)
	(loaded grapes red-truck l0)
	(loaded grapes blue-truck l0)
	(loaded lemons red-truck l0)
	(loaded lemons blue-truck l0)
	(loaded strawberries red-truck l0)
	(loaded strawberries blue-truck l0)
	(loaded oranges red-truck l0)
	(loaded oranges blue-truck l0)
	(loaded mangos red-truck l0)
	(loaded mangos blue-truck l0)
	(connected shoprite marketbasket)
	(connected marketbasket shoprite)
	(connected jefferson marketbasket)
	(connected marketbasket jefferson)
	(on-sale blueberries shoprite l1)
	(on-sale apples shoprite l2)
	(on-sale grapes shoprite l1)
	(on-sale lemons shoprite l2)
	(on-sale strawberries shoprite l3)
	(on-sale oranges shoprite l2)
	(on-sale mangos shoprite l3)
	(on-sale blueberries marketbasket l0)
	(on-sale apples marketbasket l0)
	(on-sale grapes marketbasket l1)
	(on-sale lemons marketbasket l0)
	(on-sale strawberries marketbasket l0)
	(on-sale oranges marketbasket l0)
	(on-sale mangos marketbasket l0)
	(at red-truck jefferson)
	(at blue-truck jefferson)
)
(:goal (and
	(stored blueberries l1)
	(stored apples l1)
	(stored grapes l1)
	(stored lemons l2)
	(stored strawberries l3)
	(stored oranges l1)
	(stored mangos l2)
))
)
