# Our main experiments configuration file.
---
APPROACHES:
  llm-standard:
    NAME: "llm-standard"
  llm-standard-plan:
    NAME: "llm-standard-plan"
  llm-standard-no-autoregress:
    NAME: "llm-standard"
    ARGS:
      - "no-llm_autoregressive_prompting"
  llm-standard-no-autoregress-plan:
    NAME: "llm-standard-plan"
    ARGS:
      - "no-llm_autoregressive_prompting"
  pyperplan-only:
    NAME: "pure-planning"
    FLAGS:
      planner: pyperplan
  fd-only:
    NAME: "pure-planning"
    FLAGS:
      planner: fastdownward
  random-actions:
    NAME: "random-actions"
ENVS:
  blocks:
    NAME: "pyperplan-blocks"
  depot:
    NAME: "pyperplan-depot"
  elevators:
    NAME: "pyperplan-elevators"
  freecell:
    NAME: "pyperplan-freecell"
  gripper:
    NAME: "pyperplan-gripper"
  logistics:
    NAME: "pyperplan-logistics"
  miconic:
    NAME: "pyperplan-miconic"
  movie:
    NAME: "pyperplan-movie"
  pegsol:
    NAME: "pyperplan-pegsol"
  rovers:
    NAME: "pyperplan-rovers"
  satellite:
    NAME: "pyperplan-satellite"
  scanalyzer:
    NAME: "pyperplan-scanalyzer"
  sokoban:
    NAME: "pyperplan-sokoban"
  tpp:
    NAME: "pyperplan-tpp"
  transport:
    NAME: "pyperplan-transport"
  woodworking:
    NAME: "pyperplan-woodworking"
  zenotravel:
    NAME: "pyperplan-zenotravel"
  dressed:
    NAME: "custom-dressed"
ARGS:
  - "debug"
FLAGS:
  num_train_tasks: 2
  num_eval_tasks: 10
START_SEED: 456
NUM_SEEDS: 5
