(define (problem dressed)
  (:domain dressed)
  (:objects person1 person2 person3 person4 person5 person6 person7 person8 person9 - person
            dress1 dress2 - dress
            sweatpants1 sweatpants2 sweatpants3 - sweatpants
            sweatshirt1 sweatshirt2 sweatshirt3 - sweatshirt
            nice-pants1 nice-pants2 nice-pants3 nice-pants4 - nice-pants
            collared-shirt1 collared-shirt2 collared-shirt3 collared-shirt4 collared-shirt5 - collared-shirt
            suit-jacket1 suit-jacket2 suit-jacket3 suit-jacket4 - suit-jacket
            )
  (:init (wearing-nothing-formal person1)
         (wearing-nothing-casual person1)
         (wearing-nothing-formal person2)
         (wearing-nothing-casual person2)
         (wearing-nothing-formal person3)
         (wearing-nothing-casual person3)
         (wearing-nothing-formal person4)
         (wearing-nothing-casual person4)
         (wearing-nothing-formal person5)
         (wearing-nothing-casual person5)
         (wearing-nothing-formal person6)
         (wearing-nothing-casual person6)
         (wearing-nothing-formal person7)
         (wearing-nothing-casual person7)
         (wearing-nothing-formal person8)
         (wearing-nothing-casual person8)
         (wearing-nothing-formal person9)
         (wearing-nothing-casual person9)
         (in-closet dress1)
         (in-closet dress2)
         (in-closet sweatpants1)
         (in-closet sweatpants2)
         (in-closet sweatpants3)
         (in-closet sweatshirt1)
         (in-closet sweatshirt2)
         (in-closet sweatshirt3)
         (in-closet nice-pants1)
         (in-closet nice-pants2)
         (in-closet nice-pants3)
         (in-closet nice-pants4)
         (in-closet collared-shirt1)
         (in-closet collared-shirt2)
         (in-closet collared-shirt3)
         (in-closet collared-shirt4)
         (in-closet collared-shirt5)
         (in-closet suit-jacket1)
         (in-closet suit-jacket2)
         (in-closet suit-jacket3)
         (in-closet suit-jacket4)
         )
  (:goal (and (attending-formal-event person3)
              (attending-casual-event person4)
              (attending-casual-event person1)
              (attending-casual-event person2)
              (attending-formal-event person8)
              (attending-formal-event person9)
              (attending-formal-event person5)
              (attending-formal-event person6)
              (attending-formal-event person7)
              ))
  )