(define (problem gripper-manual-1)
   (:domain gripper-strips)
   (:objects rooma roomb my-ball15 my-ball19 my-ball32 left right)
   (:init (room rooma)
          (room roomb)
          (ball my-ball15)
          (ball my-ball19)
          (ball my-ball32)
          (at-robby rooma)
          (free left)
          (free right)
          (at my-ball15 rooma)
          (at my-ball19 rooma)
          (at my-ball32 rooma)
          (gripper left)
          (gripper right))
   (:goal (and (at my-ball15 roomb)
               (at my-ball19 roomb)
               (at my-ball32 roomb)
          )
   )
)
